{{- /* Render ServiceEntries for additionalIssuers */ -}}
{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.additionalIssuers -}}
{{- range .Values.additionalIssuers }}
{{- $hostname := include "authservice.hostnameFromUri" .jwks_uri }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ $hostname | replace "." "-" }}-issuer
  namespace: {{ $.Release.Namespace }}
spec:
  hosts:
    - {{ $hostname }}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      protocol: TLS
      name: https
---
{{- end -}}
{{- end -}}
